# Generated by Django 6.1.1 on 2026-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('raw_html', models.TextField(blank=True)),
                ('clean_text', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
